### ISSUE TITLE
Create Tribute Funds page

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#28]
Current page (for content): http://www.cancervaccine.org.uk/tributefunds.html
- This page should live under **Donate**
- Page should be based on collections, [see this link for help](https://github.com/CancerVaccine/cancervaccine.github.io/issues/19#issuecomment-217860720)

**Comment by hemdagem** [comment]
I've added this to donate page, it needs each file to be updated so the content displays correctly.

**Comment by hemdagem** [comment]
updated content. Done for now, will need some changes later.

**Comment by hemdagem** [comment]
Added text from existing site across. We still need to add in the images and possibly decide the layout
