### ISSUE TITLE
Donate page

### ISSUE THREAD

**Issue by bingnz** [CancerVaccine/cancervaccine.github.io#38]
We need to implement the donate page and reuse the donate widgets that were on the home page (perhaps they stay there as well).

**Comment by robbigs** [comment]
I have had to hide the quick links because they do not work properly.  This is because of the fixed header so I will put in a story to re-instate them once I can think of a way of doing this nicely without loads of javascript

**Comment by Workshop2** [comment]
Thanks @robbigs
