### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#39]
![mobile homepage](https://cloud.githubusercontent.com/assets/19264436/15183588/910911d0-1789-11e6-95a9-958ae12a0af3.jpg)

![homepage desktop](https://cloud.githubusercontent.com/assets/19264436/15183251/2067d9da-1788-11e6-9878-ffb4881acf95.jpg)

![image](https://cloud.githubusercontent.com/assets/19264436/15183824/b065937c-178a-11e6-93a6-387bb8ca9e1f.png)

![image](https://cloud.githubusercontent.com/assets/19264436/15183864/d6aed5ac-178a-11e6-88cd-b17329a2f549.png)

**Comment by Workshop2** [comment]
Looks like another hero image here (lady picture) #54

**Comment by Workshop2** [comment]
Don't include carousel in this issue

**Comment by robbigs** [comment]
Made a start, the support us section needs to be finished.

**Comment by Workshop2** [comment]
Please create the correct size images for banner images at each resolution and compress once they have been finalised
