### ISSUE TITLE
Related content module

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#43]
As discussed please mirror WFs
The basic idea for these modules is to encourage the user to navigate further through the site. So when on a page for example Research Projects the modules at the bottom of the page should show what else is in that section. It would be Case studies & Research history

http://grape-beech1.cloudvent.net/our-research/research-projects/
![image](https://cloud.githubusercontent.com/assets/19264436/15175567/d683085e-175e-11e6-9442-05efad83a8c2.png)

**Comment by marusiaa** [comment]
Removed the navigation which is duplicated with the page targeted.

**Comment by yetanotherchris** [comment]
:+1:  lgtm
