### ISSUE TITLE
add Logo

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#47]
Decktop & Tablet landscape
![image](https://cloud.githubusercontent.com/assets/19264436/15178145/d4f68f08-176b-11e6-9f18-824922b1a50f.png)

Tablet portrait and mobile
![image](https://cloud.githubusercontent.com/assets/19264436/15178037/2bdfc0ec-176b-11e6-93a6-5be04637cfd5.png)

**Comment by hemdagem** [comment]
added logos, need to check all viewports

**Comment by Workshop2** [comment]
need to get latest logo from Marie

**Comment by Workshop2** [comment]
Updated to the following:
![desktop-logo](https://cloud.githubusercontent.com/assets/1476513/18312427/a3ef55ea-7501-11e6-85b5-f0f3a7e00f4f.png)
