### ISSUE TITLE
Hero images

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#54]
Fundraising page
![image](https://cloud.githubusercontent.com/assets/19264436/15186582/7d34b022-1795-11e6-88d6-0b7be2826975.png)

Research projects page & research history page
![image](https://cloud.githubusercontent.com/assets/19264436/15187204/20976794-1798-11e6-853a-5c283051d23e.png)

Case studies
Current image but darker

Donate

![image](https://cloud.githubusercontent.com/assets/19264436/15187188/0fbf4b80-1798-11e6-91ee-f77b202bf5bb.png)

**Comment by hemdagem** [comment]
@jazbinda I have added these in now. Have a look. We may need to adjust the position of the page.
