### ISSUE TITLE
Collect images for hero images

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#60]
Need to talk to Marie to expense the following images found in:
#54 
#39

**Comment by Workshop2** [comment]
http://www.shutterstock.com/pic-344201303/stock-photo-group-of-diverse-hands-together-joining-concept.html?src=9jj1VEg5oTub4q2QZalo1Q-1-22

http://www.shutterstock.com/pic-273553727/stock-photo-a-researcher-is-testing-dropping-reagent-to-test-tube-at-laboratory-with-chemical-equations-and-periodic-table-background.html?src=C-Vrla0xmq-W-wy9nBl6NQ-1-64

http://www.shutterstock.com/pic-112184054/stock-photo-atlanta-ga-usa-april-28-2012-a-group-of-unidentified-women-competing-in-the-dirty-girl-mud-run-splash-through-mud-as-they-near-the-finish-line-of-the-women-only-race-on-april-28.html?src=44bU3iuzOZjULE_ddXfP1g-1-42

**Comment by Workshop2** [comment]
Pricing for shutterstock:
     http://www.shutterstock.com/subscribe?clicksrc=header

£32 for 5 images
£139 for 25 images

**Comment by Workshop2** [comment]
Selfie image is getty images...would be good to get them all from one source.

Here are some alternatives:
https://www.shutterstock.com/search?searchterm=selfie+adventure&search_source=base_search_form&language=en&page=1&sort=popular&image_type=all&category=People&safe=true

@jazbinda could you choose one to replace this: https://cloud.githubusercontent.com/assets/19264436/15183824/b065937c-178a-11e6-93a6-387bb8ca9e1f.png

**Comment by jazbinda** [comment]
Can we please wait until tomorrow to buy images as they were all placeholders for now

**Comment by Workshop2** [comment]
@jazbinda: ok...woops, I have gotten the top 3 image, compressed and plumbed them into the site. We will leave everything else until tomorrow.
