### ISSUE TITLE
Donate and Support us modules

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#76]
All left aligned Donate and Support us modules which appear on most pages need tweaking as per WFs

![image](https://cloud.githubusercontent.com/assets/19264436/18350431/d9a5f2da-75cd-11e6-98f7-95041aad489d.png)
![image](https://cloud.githubusercontent.com/assets/19264436/18350699/f813f216-75ce-11e6-8d1a-be724555a6e3.png)

**Comment by yetanotherchris** [comment]
87e0af3a80eecbe4991461506c13e4e9f3236bd9
