### ISSUE TITLE
Update about us page with content from Marie

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#82]
Some people have left, we have new images.

Please compress images

**Comment by lucianbor** [comment]
Requirements:
- rename "Research Team" into "Bench workers – meet the scientists";
- update the scientists photos and text;

**Comment by Workshop2** [comment]
duplicate of #10 and #46

**Comment by lucianbor** [comment]
TODO:
- we need Emma Sparrow's photo to upload it in "/assets/images/research-team/" folder. Name file "emma-sparrow.jpg" and it will automatically picked up and displayed in the "about us" page

**Comment by lucianbor** [comment]
uploaded Emma Sparrow's photo
