### ISSUE TITLE
Maps on contact us page has stopped working

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#87]

**Comment by hemdagem** [comment]
Which maps?

**Comment by Workshop2** [comment]
http://letskickcancernow.com/contact-us

**Comment by sarabee107** [comment]
Google maps api now requires an api key; even for free use.  You need to register and get the key and then the page can be updated

**Comment by Qarj** [comment]
Added an API key and locked down to http://icvi.org.uk
