### ISSUE TITLE
Homepage tweak - Fundraisng image

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#88]
We still have layout issues with the homepage but as a minimum before going live can we please move the fundraising image so we don't cut faces out please. Also have the same issue on the fundraising page

Thanks

![image](https://cloud.githubusercontent.com/assets/19264436/18408472/8e01f6b0-7728-11e6-8a7d-e392616a151b.png)

**Comment by Workshop2** [comment]
Sorted
