### ISSUE TITLE
Donation links to use JustGiving

### ISSUE THREAD

**Issue by Workshop2** [CancerVaccine/cancervaccine.github.io#9]
Paypal is bad for the company, we need to use something that gives them tax breaks

https://www.justgiving.com/cancervaccine

**Comment by floradu88** [comment]
Yes, I know, but they will have alternatives. This is still WIP. Not yet done.

**Comment by Workshop2** [comment]
Cool, I just wanted to document this somewhere :smile:

**Comment by Workshop2** [comment]
Found a way of generating links via: https://www.justgiving.com/developer/simple-donation-integration/linkbuilder/charity
