### ISSUE TITLE
Layout tweeks

### ISSUE THREAD

**Issue by jazbinda** [CancerVaccine/cancervaccine.github.io#94]
Please mirror the spacing in the Changing Lives Through Research section above. I.e move the 'Support Us' section copy up
![image](https://cloud.githubusercontent.com/assets/19264436/19414011/409647b0-9338-11e6-9e76-d42695042b66.png)

PLease address the mobile view layout to mirror the desktop
![img_2383](https://cloud.githubusercontent.com/assets/19264436/19414027/d10ddf1a-9338-11e6-8840-0a37ff1d36be.PNG)
![img_2382](https://cloud.githubusercontent.com/assets/19264436/19414030/d2b9e908-9338-11e6-8a64-ce76d5fee6ec.PNG)

Thanks Simon your amazing!

**Comment by sarabee107** [comment]
Closing this as the complete redesign of the homepage makes this issue redundant
